from typing import List
import json

import pandas as pd
from matchms import Spectrum
from matchms.importing import load_from_mgf, load_from_msp


# TODO
OZID_FILE_PATH = ""
STRUCTURE_FILE_PATH = ""


class ReferenceLipid:
    def __init__(
        self,
        primary_annotated_name: str,
        structure_annotated_name: str,
        fragment_mz_delta: List[float],
        fragment_fatty_acid_pos: List[int], # Δ-position
        fragment_types: List[str] # `aldehyde`` or `criegee`
    ):
        self.primary_annotated_name = primary_annotated_name
        self.structure_annotated_name = structure_annotated_name
        self.fragment_mz_delta = fragment_mz_delta
        self.fragment_fatty_acid_pos = fragment_fatty_acid_pos
        self.fragment_types = fragment_types


class DatabaseLoader:

    def __init__(
        self,
        ozid_database_file: str
    ):
        self.ozid_database_file = ozid_database_file

    def load_reference_database(self) -> pd.DataFrame:
        """
        """
        df_reference = self._load_ozonolysis_prodcut_database()
        return df_reference

    def _load_ozonolysis_prodcut_database(self) -> pd.DataFrame:
        """Load ozonolysis product database."""
        with open(self.ozid_database_file, "r") as f:
            delta_mass_list = json.load(f)
        df = pd.DataFrame().from_records(delta_mass_list)
        df = df.rename(columns={
                "chain_shorthand": "primary_annotated_name",
                "db_shorthand": "structure_annotated_name",
                "delta_mass": "fragment_mz_delta",
                "fatty_acid_pos": "fragment_fatty_acid_pos",
                "fragment_type": "fragment_types"
            })
        return df


class DataLoader:

    def __init__(
        self,
        ms1_file: str,
        ms2_file: str,
        ms1_file_type: str = "mzmine",
        ms2_file_type: str = "mgf"
    ):
        self.ms1_file = ms1_file
        self.ms2_file = ms2_file
        self.ms1_file_type = ms1_file_type
        self.ms2_file_type = ms2_file_type

    def load_ms1_peak_table(self) -> pd.DataFrame:
        """"""
        match self.ms1_file_type:
            case "mzmine":
                df_ms1 = self._load_mzmine_peak_table()
            case "msdial":
                df_ms1 = self._load_msdial_peak_table()

        return df_ms1

    def _load_mzmine_peak_table(self) -> pd.DataFrame:
        """Load MS1 peak table file generated by mzmine."""
        df = pd.read_csv(self.ms1_file, low_memory=False)
        feature_cols = [
            "id", "rt", "mz",
            "spectral_db_matches:compound_name", "spectral_db_matches:ion_adduct", #"spectral_db_matches:cosine_score",
            #"spectral_db_matches:mol_formula", "spectral_db_matches:smiles", "spectral_db_matches:inchi"
        ]
        data_cols = df.columns[df.columns.str.match("datafile.*area")].to_list()
        df_data = df[data_cols].fillna(0.0)

        df_vars = df[feature_cols]
        df_vars = df_vars.sort_values(["rt", "mz"], ascending=[True, True])
        df_vars.columns = df_vars.columns.str.replace(r"spectral_db_matches:", "")
        df_vars = df_vars.rename(columns={
                                    "id": "feature_id",
                                    "mz": "precursor_mz",
                                    "ion_adduct": "adduct",
                                    "compound_name": "primary_annotated_name"
                                })
        df_vars = df_vars.fillna("")
        
        ms1_table = pd.concat([df_vars, df_data],axis=1)
        ms1_table["feature_id"] = ms1_table["feature_id"].astype(str)
        
        return ms1_table

    def _load_msdial_peak_table(self) -> pd.DataFrame:
        # TODO
        pass

    def load_ms2_spectrum(self) -> List[Spectrum]:
        """Load MS/MS spectra file."""
        match self.ms2_file_type:
            case "mgf":
                ms2_spectra = self._load_spectrum_from_mgf()
            case "msp":
                ms2_spectra = self._load_spectrum_from_msp()

        return ms2_spectra

    def _load_spectrum_from_mgf(self) -> List[Spectrum]:
        """Load MS/MS spectra from mgf file."""
        spectra = list(load_from_mgf(self.ms2_file))
        return spectra

    def _load_spectrum_from_msp(self) -> List[Spectrum]:
        """Load MS/MS spectra from msp file."""
        spectra = list(load_from_msp(self.ms2_file))
        return spectra



