rt_tol: 0.5
rt_tol_mode: absolute
mz_tol: 1.0
mz_tol_mode: Da
ms2_spectrum_similarity_type: None
score_threshold: 0.0
sn_threshold: 2.0
top_n: 10
remove_false_positive: true
base_out_dir: example/hyperparams_opt/Hela
equalize_weights: false
weight_step: 0.1
rt_weight: 0.8
precursor_mz_weight: -0.6000000000000001
spec_weight: 0.8
out_dir: example/hyperparams_opt/Hela/unequal_param_set_9
